[versions]
io-papermc-paper-api-version = "1.20.4-R0.1-SNAPSHOT"
com-velocitypowered-velocity-api-version = "3.3.0-SNAPSHOT"
dev-slne-data-api-version = "5.4.3-SNAPSHOT"
dev-slne-api-version = "1.0-SNAPSHOT"
net-luckperms-api-version = "5.4"
me-devnatan-inventory-framework-version = "3.1.0-rc"

[libraries]
io-papermc-paper-api = { module = "io.papermc.paper:paper-api", version.ref = "io-papermc-paper-api-version" }
com-velocitypowered-velocity-api = { module = "com.velocitypowered:velocity-api", version.ref = "com-velocitypowered-velocity-api-version" }
dev-slne-data-api = { module = "dev.slne:surf-data-api", version.ref = "dev-slne-data-api-version" }
dev-slne-surf-api-core-api = { module = "dev.slne.surf:surf-api-core-api", version.ref = "dev-slne-api-version" }
dev-slne-surf-api-bukkit-api = { module = "dev.slne.surf:surf-api-bukkit-api", version.ref = "dev-slne-api-version" }
dev-slne-surf-api-velocity-api = { module = "dev.slne.surf:surf-api-velocity-api", version.ref = "dev-slne-api-version" }
net-luckperms-api = { module = "net.luckperms:api", version.ref = "net-luckperms-api-version" }
me-devnatan-inventory-framework-paper = { module = "me.devnatan:inventory-framework-platform-paper", version.ref = "me-devnatan-inventory-framework-version" }
me-devnatan-inventory-framework-bukkit = { module = "me.devnatan:inventory-framework-platform-bukkit", version.ref = "me-devnatan-inventory-framework-version" }
